// Add your Odds API Key here to fetch live World Cup outright odds
// Get a free key at: https://the-odds-api.com/
export const THE_ODDS_API_KEY = 'c356a56d070a2b22a64b6a5f88bc2b45';

export const initialParticipants = [
  { id: 1, name: 'Etta', initials: 'ET', color: '#10b981', countries: [{ name: 'Jordan', code: 'jo', status: 'active' }, { name: 'South Africa', code: 'za', status: 'active' }, { name: 'Congo DR', code: 'cd', status: 'active' }, { name: 'Senegal', code: 'sn', status: 'active' }, { name: 'Paraguay', code: 'py', status: 'active' }, { name: 'New Zealand', code: 'nz', status: 'active' }, { name: 'Portugal', code: 'pt', status: 'active' }, { name: 'Belgium', code: 'be', status: 'active' }] },
  { id: 2, name: 'Isobel', initials: 'IS', color: '#3b82f6', countries: [{ name: 'France', code: 'fr', status: 'active' }, { name: 'Curacao', code: 'cw', status: 'active' }, { name: 'Bosnia & Herzegovina', code: 'ba', status: 'active' }, { name: 'Uzbekistan', code: 'uz', status: 'active' }, { name: 'South Korea', code: 'kr', status: 'active' }, { name: 'Netherlands', code: 'nl', status: 'active' }, { name: 'Spain', code: 'es', status: 'active' }, { name: 'Ghana', code: 'gh', status: 'active' }] },
  { id: 3, name: 'Monty', initials: 'MO', color: '#f59e0b', countries: [{ name: 'Morocco', code: 'ma', status: 'active' }, { name: 'Iran', code: 'ir', status: 'active' }, { name: 'Mexico', code: 'mx', status: 'active' }, { name: 'Qatar', code: 'qa', status: 'active' }, { name: 'Cape Verde Islands', code: 'cv', status: 'active' }, { name: 'Algeria', code: 'dz', status: 'active' }, { name: 'Switzerland', code: 'ch', status: 'active' }, { name: 'Croatia', code: 'hr', status: 'active' }] },
  { id: 4, name: 'Arlo', initials: 'AR', color: '#ef4444', countries: [{ name: 'Australia', code: 'au', status: 'active' }, { name: 'Austria', code: 'at', status: 'active' }, { name: 'Scotland', code: 'gb-sct', status: 'active' }, { name: 'Argentina', code: 'ar', status: 'active' }, { name: 'Iraq', code: 'iq', status: 'active' }, { name: 'Uruguay', code: 'uy', status: 'active' }, { name: 'Brazil', code: 'br', status: 'active' }, { name: 'Tunisia', code: 'tn', status: 'active' }] },
  { id: 5, name: 'Caro', initials: 'CA', color: '#8b5cf6', countries: [{ name: 'England', code: 'gb-eng', status: 'active' }, { name: 'Saudi Arabia', code: 'sa', status: 'active' }, { name: 'Haiti', code: 'ht', status: 'active' }, { name: 'Norway', code: 'no', status: 'active' }, { name: 'Egypt', code: 'eg', status: 'active' }, { name: 'United States', code: 'us', status: 'active' }, { name: 'Ecuador', code: 'ec', status: 'active' }, { name: 'Canada', code: 'ca', status: 'active' }] },
  { id: 6, name: 'Dom', initials: 'DO', color: '#ec4899', countries: [{ name: 'Sweden', code: 'se', status: 'active' }, { name: 'Japan', code: 'jp', status: 'active' }, { name: 'Czech Republic', code: 'cz', status: 'active' }, { name: 'Cote d\'Ivoire', code: 'ci', status: 'active' }, { name: 'Panama', code: 'pa', status: 'active' }, { name: 'Germany', code: 'de', status: 'active' }, { name: 'Colombia', code: 'co', status: 'active' }, { name: 'Turkey', code: 'tr', status: 'active' }] }
];
